version: "3"

services:
  web:
    build: .

    depends_on:
      - db

    restart: always

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: ${DATABASE_URL}

    command: bash -c "sleep 10 && npm install --only=prod && npm run dev"

    volumes:
      - ./dist:/usr/src/api-express-auth/dist
      - ./package.json:/usr/src/api-express-auth/package.json

    networks:
      - api-express

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "49555:5432"

    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data

    networks:
      - api-express

networks:
  api-express:
    driver: bridge
